---
- name: Remove Users to the IDM Massive
  hosts: all

  tasks:
  - name: Delete Users Massive
    ipa_user:
      name: "{{ item.name }}"
      state: absent
      ipa_host: idm.lab.example.net
      ipa_user: admin
      ipa_pass: topsecret
    with_items:
      - { name: david }
      - { name: mauricio }
      - { name: juan }
