---
- name: Add Users to the IDM Massive
  hosts: all
  collections:
    - freeipa.ansible_freeipa

  tasks:
  - name: Load Users users_present.json
    include_vars:
      file: users_present.json

  - name: Create Users
    ipa_user:
      users: "{{ users }}"
      ipa_host: idm.lab.example.ne
      ipa_user: admin
      ipa_pass: topsecret
