---
- name: Add Users to the IDM Massive
  hosts: all

  tasks:
  - name: Load Users users_present.json
    include_vars:
      file: users_present.json

  - name: Create Users
    ipa_user:
      name: "{{ item }}"
      state: present
      ipa_host: idm.lab.example.ne
      ipa_user: admin
      ipa_pass: topsecret
    with_items:
      - david
      - mauricio
      - juan
