---
- name: Add Users to the IDM Massive
  hosts: all

  tasks:
  - name: Create Users Massive
    ipa_user:
      name: "{{ item.name }}"
      givenname: "{{ item.givenname }}"
      sn: "{{ item.sn }}"
      password: zounds
      state: present
      update_password: on_create
      ipa_host: idm.lab.example.net
      ipa_user: admin
      ipa_pass: topsecret
    with_items:
      - { name: david, givenname: David, sn: Goz }
      - { name: mauricio, givenname: Mauricio, sn: Pal }
      - { name: juan, givenname: Juan, sn: Nar }

