- name: Add Users to the IDM
  hosts: all
  gather_facts: false

  tasks:
  - name: Load Users users_present.json
    include_vars:
      file: users_present.json

  - name: Create Users
    ipauser:
      ipaadmin_password: Test123!
      users: "{{ users }}"
